version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000

  models:
    build: ./models
    volumes:
      - ./models:/app
    ports:
      - "8002:8000"


  test-schema-encoder:
    build: ./test-schema-encoder
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - ./test-schema-encoder:/app
